# -*- coding: utf-8 -*-
"""Cópia de Atividade 3 - Simulação de Monte Carlo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sm2Z1BN-7MLRxd4QGd_nDpCxJn7i65XO

# **Simulação de Monte Carlo - Caso TechToy**
1. **Introdução e Contexto**

A empresa TechToy está prestes a lançar um novo drone no mercado. A diretoria está em dúvida entre duas estratégias de lançamento e contratou você, analista de dados, para realizar uma Simulação de Monte Carlo.

O objetivo é entender não apenas o lucro esperado, mas o risco de prejuízo de cada decisão.

As Estratégias:
Estratégia A (Conservadora): Foca em um público de nicho, com preço mais alto e vendas mais previsíveis.

Estratégia B (Agressiva): Foca em escala, com preço menor, mas com custos de produção e volume de vendas muito mais incertos.

**2. Base de Dados e Parâmetros**

Execute a célula abaixo para carregar as bibliotecas necessárias e os parâmetros oficiais fornecidos pelo departamento financeiro.
"""

import numpy as np
import matplotlib.pyplot as plt

# Configurações da Simulação
N_SIMULACOES = 10000

# --- PARÂMETROS ESTRATÉGIA A ---
vendas_media_a = 500
vendas_desvio_a = 50
custo_min_a = 600
custo_max_a = 700
preco_venda_a = 1200
investimento_fixo_a = 50000

# --- PARÂMETROS ESTRATÉGIA B ---
vendas_media_b = 800
vendas_desvio_b = 250
custo_min_b = 400
custo_max_b = 800
preco_venda_b = 1000
investimento_fixo_b = 150000

print("Parâmetros carregados com sucesso!")

"""3. Desafio

**1: Modelagem do Lucro**

Crie uma função ou um script que utilize os parâmetros acima para gerar 10.000 resultados possíveis de lucro para cada estratégia.Dicas:Para as Vendas, use uma distribuição Normal: np.random.normal(media, desvio, N_SIMULACOES).Para o Custo Unitário, use uma distribuição Uniforme: np.random.uniform(min, max, N_SIMULACOES).

A fórmula do lucro é:

$Lucro = (Vendas \times Preço) - (Vendas \times Custo\_Unitário) - Investimento\_Fixo$
"""

simulacoes = 10000
media_vendas_a = 500
desvio_vendas_a = 50
preco_a = 2000
custo_min_a = 600
custo_max_a = 800
investimento_a = 200000
vendas_a = np.random.normal(media_vendas_a, desvio_vendas_a, simulacoes)
custos_a = np.random.uniform(custo_min_a, custo_max_a, simulacoes)
lucro_a = (vendas_a * preco_a) - (vendas_a * custos_a) - investimento_a

media_vendas_b = 800
desvio_vendas_b = 200
preco_b = 1500
custo_min_b = 500
custo_max_b = 1000
investimento_b = 300000
vendas_b = np.random.normal(media_vendas_b, desvio_vendas_b, simulacoes)
custos_b = np.random.uniform(custo_min_b, custo_max_b, simulacoes)
lucro_b = (vendas_b * preco_b) - (vendas_b * custos_b) - investimento_b

"""**2: Visualização dos Resultados**

Gere um histograma comparando as duas estratégias. O gráfico deve ajudar a diretoria a visualizar onde o lucro se concentra e onde estão os riscos de perda (valores abaixo de zero).
"""

plt.figure(figsize=(10,5))
plt.hist(lucro_a, bins=50, alpha=0.5, label='Estratégia A')
plt.hist(lucro_b, bins=50, alpha=0.5, label='Estratégia B')
plt.axvline(0)  # linha do prejuízo
plt.title('Simulação de Lucro - Monte Carlo')
plt.xlabel('Lucro')
plt.ylabel('Frequência')
plt.legend()
plt.show()

"""**3: Cálculo de Probabilidades**
Calcule e exiba as seguintes métricas para cada estratégia:

Média de Lucro.

Probabilidade de Prejuízo (porcentagem de simulações onde o lucro foi < 0).
"""

media_a = np.mean(lucro_a)
media_b = np.mean(lucro_b)
prejuizo_a = (lucro_a < 0).mean() * 100
prejuizo_b = (lucro_b < 0).mean() * 100

print("Estratégia A")
print("Lucro médio:", round(media_a, 2))
print("Chance de prejuízo:", round(prejuizo_a, 2), "%")
print("\nEstratégia B")
print("Lucro médio:", round(media_b, 2))
print("Chance de prejuízo:", round(prejuizo_b, 2), "%")